[View in Colaboratory](https://colab.research.google.com/github/duakaran96/ML-AcadView/blob/master/Assignment_2.ipynb)

#Imports

In [0]:
import numpy as np

**Q.1 - Create a numpy array with 10 elements of the shape(10,1) using np.random and find out the mean of the elements using basic numpy functions.**

In [0]:
ar = np.random.randn(10,1)

The array

In [6]:
ar

array([[-1.240294  ],
       [-0.87181222],
       [-0.14564134],
       [ 0.70699376],
       [ 0.40181967],
       [-1.93744974],
       [ 0.68466724],
       [-0.34898315],
       [-0.08273683],
       [ 1.27240211]])

Mean of elements

In [7]:
ar.mean()

-0.15610345179370966

**Q.2 - Create a numpy array with 20 elements of the shape(20,1) using np.random find the variance and standard deviation of the elements.**

In [8]:
li = np.random.rand(20,1)
li

array([[0.5017977 ],
       [0.24562945],
       [0.10795245],
       [0.21664375],
       [0.95920129],
       [0.43741228],
       [0.93431604],
       [0.52241598],
       [0.15152172],
       [0.31546856],
       [0.18141243],
       [0.97130254],
       [0.46866992],
       [0.59356901],
       [0.62912916],
       [0.24925166],
       [0.16609394],
       [0.70150758],
       [0.09763907],
       [0.66314351]])

Standard deviation

In [9]:
li.std()

0.2803908255843374

Variance

In [10]:
li.var()

0.07861901507186632

**Q.3 - Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random. Print the matrix which is the matrix multiplication of A and B. The shape of the new matrix should be (10,25). Using basic numpy math functions only find the sum of all the elements of the new matrix.**

In [12]:
A = np.random.rand(10, 20)
B = np.random.rand(20, 25)
C = np.dot(A, B)
print(C)
print()
print("Shape of C")
print(C.shape)

[[5.37382076 3.33745447 3.60279692 5.48122328 4.25448476 4.90774886
  4.04993931 3.21945048 2.8566731  4.97296201 4.05093637 4.20761674
  4.31541819 3.64885689 4.35555115 4.97625305 4.45751228 3.48452115
  5.70712932 3.67670241 3.92690276 3.54478542 3.56323874 4.1656687
  4.23540197]
 [6.81015624 5.09461716 4.82223409 6.01514851 4.71098404 5.0835043
  5.47433123 5.09821392 3.59954514 5.94672623 4.70694769 5.17373852
  4.44984859 4.77544691 4.46960711 6.41257433 5.31473957 4.64693739
  6.39348545 4.81678756 4.47723513 5.68969601 4.65207203 4.89070588
  4.94839945]
 [6.71417719 5.04589977 3.86701631 6.21486408 4.69049099 4.86608389
  4.4849141  4.00626388 2.69694936 5.75451131 4.08682159 5.29342422
  4.4775369  4.12992001 5.65505458 6.14110806 4.83299565 4.88514593
  5.1095984  4.79551286 4.0528344  5.06928299 3.86361669 4.74483599
  4.55077282]
 [5.68407927 4.27419731 3.77377817 5.42210235 4.32692082 3.67223372
  3.67316823 3.85715103 2.94555325 5.08501773 3.76888374 3.76929143
  3.8755

Sum of all elements

In [13]:
np.sum(C)

1208.6441586258243

**Q.4 - Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of shape(10,1) such that each element is the following function applied on each element of A. **

f(x)=1 / (1 + exp(-x))

In [0]:
a = np.arange(10).reshape(10,1)
b = np.empty_like(a)
b = 1/(1 + np.exp(-a))

In [15]:
print(a)
print(b)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[0.5       ]
 [0.73105858]
 [0.88079708]
 [0.95257413]
 [0.98201379]
 [0.99330715]
 [0.99752738]
 [0.99908895]
 [0.99966465]
 [0.99987661]]
